on:
  push:
    branches:
      - '*.v7'
  pull_request:
    branches:
      - '*.v7'
name: Test v7
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [ubuntu-latest]
    name: Run ${{ matrix.go-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Prepare tests
      run: |
        sudo apt-get install -y netcat
        sudo sysctl -w vm.max_map_count=262144
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Docker containers
      run: docker-compose up -d
    - name: Check Docker containers
      run: docker ps -a
    - name: Get dependencies
      run: |
        go get -u github.com/google/go-cmp/cmp
        go get -u github.com/fortytw2/leaktest
        go get . ./aws/... ./config/... ./trace/... ./uritemplates/...
    - name: Wait for Elasticsearch
      run: |
        while ! nc -z localhost 9200; do sleep 1; done
        while ! nc -z localhost 9210; do sleep 1; done
    - name: Run the tests
      run: |
        go test -race -deprecations -strict-decoder -v . ./aws/... ./config/... ./trace/... ./uritemplates/...
